PRE_GAME_DURATION = 30
DAY_SPEECH = 60
DAY_NOMINATION_EXTRA = 15

DEFENSE_DURATION = 60
VOTING_DURATION = 30
DEFENSE_TIE_DURATION = 30
VOTING_TIE_DURATION = 30
LAST_WORDS_DURATION = 60

NIGHT_MAFIA_CHAT = 60
NIGHT_MAFIA_EXTRA = 15
NIGHT_DON_DURATION = 30
NIGHT_SHERIFF_DURATION = 30
NIGHT_DOCTOR_DURATION = 30

MIN_PLAYERS = 6
MAX_PLAYERS = 9